language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  # - rbx
gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-3
before_install:
  - curl -# https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.0.1.tar.gz | tar xz -C /tmp
before_script:
  - TEST_CLUSTER_COMMAND="/tmp/elasticsearch-1.0.1/bin/elasticsearch" rake elasticsearch:start