# -------------------------------------------------------------------------------
# Configuration file for http://travis-ci.org/#!/elasticsearch/elasticsearch-ruby
# -------------------------------------------------------------------------------

language: ruby

branches:
  only:
    - master

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0

jdk:
  - openjdk7

env:
  - TEST_SUITE=unit
  - TEST_SUITE=integration

install:
  - test $TEST_SUITE == 'integration' && curl -# https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.7.tar.gz | tar xz -C /tmp || true

before_script:
  - git submodule update --init --recursive
  - rake test:update
  - rake test:bundle
  - test $TEST_SUITE == 'integration' && TEST_CLUSTER_COMMAND="/tmp/elasticsearch-0.90.7/bin/elasticsearch" rake test:server:start || true

script:
  - "rake test:$TEST_SUITE"

matrix:
  exclude:
    - rvm: 1.8.7
      jdk: openjdk7
      env: TEST_SUITE=integration

notifications:
  disable: true
